### PR TITLE
Middleware auth

### PR DESCRIPTION
**Pull request by DevParmar1**

### CODE REVIEW

**Comment by batflarrow** [comment]
Can you resolve the conflicts once and also for dotenv you don't have to include it in all the files it only needs to be called once at the beginning.

**Comment by batflarrow** [comment]
> @DevParmar1  Can you resolve the conflicts once and also for dotenv you don't have to include it in all the files it only needs to be called once at the beginning.

**Comment by DevParmar1** [comment]
Resolved

**Comment by batflarrow** [comment]
> Resolved

There is a mongodb url in the database connection file @DevParmar1 is it yours..?

**Comment by DevParmar1** [comment]
Yeah, I had committed it accidentally but have removed it on the next commit.

**Comment by DevParmar1** [comment]
Review the final changes!

**Pull request merged**
