### PR TITLE
 Create endpoints for CRUD operations on question database

### PR DESCRIPTION
**Pull request by JoelLau**
Issue #4

### CODE REVIEW

**Comment by Shreyansh-Mishra** [comment]
The readQuestions and readQuestion function should not return the whole question as it will contain the answer field too, instead return the essential fields like text, image, link, points, id, and category along with a success message.

**Comment by JoelLau** [comment]
I've hidden the `answer` field from the responses, but would like to clarify - 

by "along with a success message", do you mean a 200 response, or do you mean something like the below:

```json
{
  "message": "Successfully retrieved questions",
  "data": [
    {
      "_id": "615801aeb1c1a8c3451cca4c",
      "text": "hello world",
      "id": 0,
      "points": 0,
      "__v": 0,
    },
  ],
};

```

**Comment by Shreyansh-Mishra** [comment]
Yes, that's what I meant, Implement it and then we can merge the PR.

**Comment by JoelLau** [comment]
got it, let me know if there're any other changes required

**Comment by JoelLau** [comment]
@Shreyansh-Mishra thanks for merging the PR! can I trouble you to add the `hacktoberfest-accepted` label as well?

**Comment by JoelLau** [comment]
thank you!

**Pull request merged**
