### PR TITLE
Added login functionality

### LINKED ISSUE #2: Implement Login Functionality

### PR DESCRIPTION
**Pull request by SwapnilSoni1999**
closes #2 

- added either username/email + password login feature
- using bcryptjs to compare saved password (signup route needs to use bcryptjs ofcourse)

### CODE REVIEW

**Comment by batflarrow** [comment]
Instead of sending the token in the response body, we want to use HTTP only cookie as mentioned in the wiki :)

**Comment by SwapnilSoni1999** [comment]
> Instead of sending the token in the response body, we want to use HTTP only cookie as mentioned in the wiki :)

sure thing i'll do

**Comment by batflarrow** [comment]
The cookie is still not HTTPonly and why don't you go ahead and update the max-age to 7 days

**Comment by batflarrow** [comment]
> > Instead of sending the token in the response body, we want to use HTTP only cookie as mentioned in the wiki :)
> 
> sure thing i'll do

The cookie is still not HTTPonly and why don't you go ahead and update the max-age to 7 days

**Comment by SwapnilSoni1999** [comment]
> > > Instead of sending the token in the response body, we want to use HTTP only cookie as mentioned in the wiki :)
> > 
> > 
> > sure thing i'll do
> 
> The cookie is still not HTTPonly and why don't you go ahead and update the max-age to 7 days

sure

**Review by batflarrow — APPROVED** [review]

**Comment by SwapnilSoni1999** [comment]
You forgot the label though :) `hacktoberfest-accepted`

**Pull request merged**
